version: '3.8'
services:
  order-service:
    build: ./microservices/order-service
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/order_db
    depends_on:
      - mongo

  payment-service:
    build: ./microservices/payment-service
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/payment_db
    depends_on:
      - mongo

  delivery-service:
    build: ./microservices/delivery-service
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/delivery_db
    depends_on:
      - mongo

  restaurant-service:
    build: ./microservices/restaurant-service
    ports:
      - "5003:5003"
    environment:
      - MONGO_URI=mongodb://mongo:27017/restaurant_db
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: