
services:
  delivery-service:
    container_name: delivery-service
    build: ./backend/microservices/delivery-service
    volumes:
      - ./backend/microservices/delivery-service:/app
    ports:
      - "5001:5001"
    env_file:
      - ./backend/microservices/delivery-service/.env

  order-service:
    container_name: order-service
    build: ./backend/microservices/order-service
    volumes:
      - ./backend/microservices/order-service:/app
    ports:
      - "5000:5000"
    env_file:
      - ./backend/microservices/order-service/.env

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0 
    stdin_open: true
    tty: true