
services:
  delivery-service:
    delivery_container_name: delivery-service
    delivery_build: ./backend/microservices/delivery-service
    delivery_volumes:
      - ./backend/microservices/delivery-service:/app
    delivery_ports:
      - "5001:5001"
    delivery_env_file:
      - ./backend/microservices/delivery-service/.env

    order-service:
    order_container_name: order-service
    order_build: ./backend/microservices/order-service
    order_volumes:
      - ./backend/microservices/order-service:/app
    order_ports:
      - "5000:5000"
    order_env_file:
      - ./backend/microservices/order-service/.env


  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true