version: '3.8'
services:
  order-service:
    build: ./microservices/order-service
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/order_db
    depends_on:
      - mongo

  payment-service:
    build: ./microservices/payment-service
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/payment_db
    depends_on:
      - mongo

  delivery-service:
    build: ./microservices/delivery-service
    ports:
      - "3003:3003"
    environment:
      - MONGO_URI=mongodb://mongo:27017/delivery_db
    depends_on:
      - mongo

  restaurant-service:
    build: ./microservices/restaurant-service
    ports:
      - "3004:3004"
    environment:
      - MONGO_URI=mongodb://mongo:27017/restaurant_db
    depends_on:
      - mongo

  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    depends_on:
      - order-service
      - payment-service
      - delivery-service
      - restaurant-service

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: